Исправляет ссылку наставника
htmlacademy-htmlcss/2189703-sedona-36 pull request #2
Opened 2023-01-18 13:52 UTC by DianaLad8

Интуитивно чувствовала, что нужны квадратные скобки, но в учебном видео Николай не исправляет кавычки, там он имитирует другую ошибку. Решила не своевольничать))

2023-01-23 07:47 UTC, DianaLad8 reviewed
Изменения последуют в следующих коммитах

2023-01-23 07:47 UTC, DianaLad8 commented on index.html
> +      <a>
Сильно подозреваю, что логотип нужно поставить внутри <nav>

2023-01-23 07:47 UTC, DianaLad8 commented on index.html
> +      <article class="description">
В последующих коммитах заменила теги статью на секцию. Добавила классы.

2023-01-23 07:47 UTC, DianaLad8 commented on index.html
> +        <ul class="description-list">
В следующем коммите поменяла список на нумерованный, согласно макету

2023-01-25 09:22 UTC, kamunicorn requested changes
По структуре (тегам) замечаний немного, но их надо исправлять сейчас.
Есть замечания по классам, их можно исправить потом ближе к стилизации.
В проекте много кнопок, но у всех стоит класс `.button`. Если стилизация будет по этому классу, стили будут конфликтовать. Надо подумать, как отделить одни кнопки от других.
👀пометила то, что надо исправлять сейчас.

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +      <a>
можно и так, и эдак

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +      <h1 class="visually-hidden">Седона - городок в Аризоне.</h1>
С заголовком хорошо получилось👍🏻(на этом моменте многие спотыкаются и делают менее красиво, хотя тоже верно)

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +        <h2 class="description-title">Седона — небольшой городок в Аризоне,
👀это скорее слоган, а не заголовок - по нему непонятно, что будет в секции. Какой тогда может быть заголовок у секции?

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +          <li class="description-item">
👀по макету мост дьявола в конце списка

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +            <img class="photo-1" src="#" alt="Фотография городка.">
Молодец, что поняла, что картинка относится к пункту списка👍🏻(иногда студенты выносят картинку за список)

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +        <h2 class="advantages-title">Приезжайте в Седону отдохнуть в комфорте и уюте!</h2>
👀скорее слоган, а не заголовок

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +        <h2 class="search-title">Заинтересовались?</h2>
Уместное использование заголовка👍🏻

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +          <button class="button button-secund" type="submit">подписаться</button>
👀`.button-secund` - если имелась ввиду кнопка второго типа, то прошу переделать на вариант без ошибки `.button-second` (неэстетично, ошибки коробят глаз)

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +        <ul class="hero-list">
👀стоит упростить в одну картинку без списка (при экспорте из фигмы можно сгруппировать 3 текста вместе), максимум - обертка дивом.
А то что в `alt` прописала текст, а не абзацем - хорошо👍🏻

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +            <p class="description-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
👀`.description-description` - какое-то громоздкое название, может список можно как-то по другому назвать?

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +            <p class="service-description">Рекомендуем пожить в настоящем мотеле,
👀`.service-description` не совсем логично: до этого мы были в списке преимуществах (`.advantages`), а теперь вдруг появились услуги (service). Надо сделать так, чтобы было понятно, что этот параграф относится к списку и связан с рядом лежащим заголовком.

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +      <header class="inner-header">
Уместное использование хэдера👍🏻

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +          <div class="buttons">
хорошо, что сгруппировала кнопки - потом легче будет стилизовать👍🏻

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +            <legend class="catalog-filter-title">Инфраструктура:</legend>
Уместное использование `legend`👍🏻

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +          <a class="button button-tile" href="#">
кнопки-ссылки определения вида лучше сгруппировать (можно потом), будет легче стилизовать

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +        <ol class="catalog-hotels" data-test="catalog">
в этом списке порядок нумерации не важен, так что `ol` не обязателен, можно несортированный список

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +            <div class="hotel-star">
Звездный рейтинг можно сделать лучше, причем разными способами.
В текущем варианте пользователь скринридера услышит: "Изображение. Звезда." (и так 4 раза) и не поймет:).
Элемент сложный, предлагаю его переделать потом, когда придет решение. А блок `.hotel-star`, наверное, так и останется

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +          <li class="pagination-item">
👀где-то тут должно быть троеточие, как оно будет выглядеть в разметке?

2023-01-25 09:22 UTC, kamunicorn commented on catalog.html
> +            <a class="button" href="https://vk.com/htmlacademy">
Эти кнопки сильно отличаются от остальных кнопок проекта, лучше задать им другой класс.

2023-01-25 09:22 UTC, kamunicorn commented on index.html
> +            <img class="photo-2" src="#" alt="Фотография Моста Дьявола.">
не очень понятное название класса

2023-01-26 08:10 UTC, DianaLad8 commented on catalog.html
> +      <header class="inner-header">
класс переименовала более уместно

2023-01-26 08:10 UTC, DianaLad8 commented on catalog.html
> +          <a class="button button-tile" href="#">
Исправила

2023-01-26 08:10 UTC, DianaLad8 commented on catalog.html
> +            <div class="hotel-star">
Я подумала, что когда буду работать с изображениями, действительно осенит)))

2023-01-26 08:10 UTC, DianaLad8 commented on catalog.html
> +          <li class="pagination-item">
Посмотрела на макете - это текст. Добавила такой же элемент списка с точками, ссылку пока оставила.

2023-01-26 08:10 UTC, DianaLad8 commented on catalog.html
> +            <a class="button" href="https://vk.com/htmlacademy">
замена класс на button-social

2023-01-26 08:10 UTC, DianaLad8 commented on index.html
> +        <h2 class="description-title">Седона — небольшой городок в Аризоне,
Изменила заголовок секции, сделала невидимым. Тексты разделила на большой и маленький.

2023-01-26 08:10 UTC, DianaLad8 commented on index.html
> +            <p class="description-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
5 раз меняла классы, и все равно неудачно. Придумала другой вариант.

2023-01-26 08:10 UTC, DianaLad8 commented on index.html
> +          <li class="description-item">
Сделала по нумерации макета - там он второй. Думала в стилях переставить. Сейчас исправила.

2023-01-26 08:10 UTC, DianaLad8 commented on index.html
> +            <img class="photo-2" src="#" alt="Фотография Моста Дьявола.">
Обозвала по номеру в макете) Сейчас исправила, как будет на рисунке.

2023-01-26 08:10 UTC, DianaLad8 commented on index.html
> +        <h2 class="advantages-title">Приезжайте в Седону отдохнуть в комфорте и уюте!</h2>
Исправила, как в предыдущей секции

2023-01-26 08:10 UTC, DianaLad8 commented on index.html
> +            <p class="service-description">Рекомендуем пожить в настоящем мотеле,
запуталась с поиском названий классов, несколько раз меняла и недоисправляля(( Сейчас поправила.

2023-01-26 08:52 UTC, kamunicorn commented on catalog.html
> +      <section class="catalog-hootels">
одна о лишняя

2023-01-26 08:52 UTC, kamunicorn commented on catalog.html
> +          <div class="button button-view">
див и ссылка внутри с одним классом `.button`. див содержит в себе набор ссылок и должен их объединять классом (кнопки изменения вида)

2023-01-26 08:53 UTC, merged