Добавляет формы,, модальное окно с тултипом.
htmlacademy-htmlcss/2189703-sedona-36 pull request #9
Opened 2023-03-02 17:29 UTC by DianaLad8

2023-03-04 11:20 UTC, kamunicorn requested changes
Хорошо получились хлебные крошки - добавляются, последний пункт не выделяется. Ссылки в главном меню теперь красиво выделяются в фокусе 👍🏻
С модалкой справились, выглядит хорошо 👍🏻, а замечания там по мелочи.
Осталось разобраться:
1. закончить с состояниями (фокус, актив) некоторых элементов.
2. размеры, бордеры, тени и остальные свойства по мелочи.
3. отключенные элементы - не должны реагировать на нажатие, сейчас реагируют почти все.
4. количество товаров в избранном.

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +          <a class="logo navigation-svg">
1. при наведении прячется под картинку
2. неактивная ссылка на главной реагирует на наведение и нажатие (прозрачность), а не должна

![image](https://user-images.githubusercontent.com/38280676/222886082-b0620018-29a3-47fb-b0ec-83171a8807db.png)

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +  background-color: #ffffff;
почему решила назвать класс `.navigation-svg` и почему ему задан фоновый цвет?

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +    <div class="modal modal-search">
`.modal-search` будет чем-то отличаться от просто `.modal`? Не вижу, что просто `.modal` используется

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> + .email.field  {
Этот .field используется еще где-нибудь?
У поля емейла нет состояний наведения, фокуса, введенного текста, только нажатие. Должно быть, как у полей дат в модалке.

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +  fill: rgba(233, 245, 5, 0.966);
что это делает? не нашла

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +/* Не работает переполнение - 20 детей уже никуда не поедет */
чуток подправить стили и можно будет взять:
![image](https://user-images.githubusercontent.com/38280676/222886875-09ee8a70-1431-4a16-91e6-467ea0749787.png)

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +  background: url(../images/icons/tooltip.svg) center no-repeat;
эту штуку можно нарисовать на css
https://up.htmlacademy.ru/htmlcss/36/book/css/css-graphics

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +          <div class="buttons-modal grown">
как используется класс .grown?

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +            <button class="button-plus button-amount" type="button">
1. как используются классы .button-minus и .button-plus? 
2. почему решила вставить плюс и минус как svg?
3. в фокусе размер обводки не по макету

в верстке получаем 40x48px:
![image](https://user-images.githubusercontent.com/38280676/222889839-db4fd1af-5b28-49eb-bddc-0b27a82b3152.png)
по макету должен быть 26px:
![image](https://user-images.githubusercontent.com/38280676/222889990-d8541f63-7066-4ccb-a6a8-e8dc20e165b3.png)

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +          <span class="date-text error">Мы не можем отправить вас в прошлое.</span>
что будет, если удалить элемент с подписью:
![image](https://user-images.githubusercontent.com/38280676/222890584-238cf9d1-49a2-4bcd-a725-95cbcc6c3674.png)
как будет задаваться отступ между строками?

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +          <span class="form-label">
какая-то большая конструкция, удалила `span.form-label` - вроде ничего не изменилось

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +              <span class="tooltip-text" role="tooltip" id="tooltip-label-date">
хорошо, что добавили роль и aria-labelledby 👍🏻
может есть еще места, куда его стоит добавить?

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +              <button class="tooltip-toggle" type="button" aria-labelledby="tooltip-label-date">
Кнопка связана с текстом тултипа и одновременно располагается в label, который связан в свою очередь с инпутом. Вот что говорит скринридер, когда я перехожу в поле ввода количества детей:
Дети (название инпута)
"Укажите количество детей..." (текст тултипа)
счетчик, редактируемый, выделено, 2
Вообще всегда сначала говорит название, потом aria-labelledby (если есть), потом значение инпута. А вот есть `aria-describedby` - если тут поменять на него, то при фокусе на инпут тултип не зачитывается.

2023-03-04 11:20 UTC, kamunicorn commented on index.html
> +            <button class="button-minus button-amount" type="button">
кнопка без подписи, скринридер озвучивает ее "кнопка"
почему решила вставить плюс и минус как svg?

2023-03-04 11:20 UTC, kamunicorn commented on index.html
>                  <span class="visually-hidden">Избранное. Вы выбрали 12 гостиниц.</span>
Хорошая формулировка 👍🏻
Для скринридеров сказали, а как это отобразить визуально, если будет 13 в избранном?

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
>  .page-container {
осталось добавить тень

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +  padding: 10px 14px;
хорошо по высоте получилось, фокус смотрится эстетичней 👍🏻

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
>  .navigation-current {
отключенная ссылка не должна реагировать на наведение и нажатие

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +.control:active {
при нажатии на отмеченный чекбокс:
![image](https://user-images.githubusercontent.com/38280676/222894679-e5a5f953-5324-490e-84f6-d8d8be085b7c.png)
как в макете:
![image](https://user-images.githubusercontent.com/38280676/222894699-889ff058-89a2-475e-89b2-a6ef57675767.png)

2023-03-04 11:20 UTC, kamunicorn commented on catalog.html
> +                      <input class="range-input range-input-till" type="number" value="0">
когда по ним кликаешь, текст немного дергается, где-то бордер появляется

2023-03-04 11:20 UTC, kamunicorn commented on catalog.html
> +                      <button class="rangle-toggle toggle-min">
при нажатии кнопки отправляется форма

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +.rangle-toggle:focus {
при фокусе
![image](https://user-images.githubusercontent.com/38280676/222895451-f2551c99-7e19-44c3-ae91-d7c888221c22.png)

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +  outline: 3px solid #000000;
стала вглядываться в макет и заметила, что у этих штучек есть стили с тенями!
![image](https://user-images.githubusercontent.com/38280676/222895518-6a1ab49b-0ba6-49d8-9b27-472bc079f2d3.png)
сама удивлена

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +.range-input-next {
еще заметила, что похоже они без бордера, между ними просто пространство по макету
![image](https://user-images.githubusercontent.com/38280676/222895751-f09bad35-8c4e-4cee-b76e-bb24d7550029.png)

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
>    outline: none;
сейчас стили фокуса и наведения одинаковые, надо, чтобы тогда оставалась браузерная обводка

2023-03-04 11:20 UTC, kamunicorn commented on styles/styles.css
> +.field:active {
![image](https://user-images.githubusercontent.com/38280676/222896621-d8250255-b63e-4b3e-9a3b-d89af0332eda.png)

2023-03-05 09:35 UTC, DianaLad8 commented on styles/styles.css
> +  background: url(../images/icons/tooltip.svg) center no-repeat;
Да, можно ромбиком, но еще время потеряю, пока размеры высчитаю, оставлю так как есть. На лайве говорили, что это лучше сделать векторным рисунком))

2023-03-05 14:22 UTC, DianaLad8 commented on styles/styles.css
> +.rangle-toggle:focus {
Отнаследовала :))

2023-03-05 15:02 UTC, DianaLad8 commented on styles/styles.css
> +  outline: 3px solid #000000;
DevTools тень зачеркивает :(

2023-03-05 15:04 UTC, DianaLad8 commented on styles/styles.css
> +  outline: 3px solid #000000;
Поменяла толщину outline при разных состояниях.

2023-03-05 15:08 UTC, DianaLad8 commented on catalog.html
> +                      <input class="range-input range-input-till" type="number" value="0">
В стилях расписала подробно))

2023-03-07 01:15 UTC, kamunicorn reviewed
Проделана большая работа! :fire: :muscle: 
Осталось добить несколько моментов:
- добавление прозрачности отмеченному чекбоксу при наведении
- тень тултипа
- тень ползунков
- количество в избранном
- поехавшие кнопки в каталоге, селект растянулся:
![image](https://user-images.githubusercontent.com/38280676/223291978-031a8a20-5195-43bf-941a-fc9556e6fa95.png)
По пиксель-перфекту глянула - все проходит, за редким исключением.

2023-03-07 01:15 UTC, kamunicorn commented on index.html
> +          <span class="visually-hidden date-text">На эти даты есть свободные номера. Пока есть.</span>
не поняла, зачем тут этот блок и почему .visually-hidden

2023-03-07 01:15 UTC, kamunicorn commented on styles/styles.css
>  .tooltip-text {
только заметила, что у тултипа тень по макету:
![image](https://user-images.githubusercontent.com/38280676/223285281-49256f3f-c258-4ccf-a219-a09912902406.png)

2023-03-07 01:15 UTC, kamunicorn commented on styles/styles.css
> +.control:active {
теперь при наведении чекбокс не просвечивает, причем у не отмеченного прозрачность меняется

2023-03-07 01:15 UTC, kamunicorn commented on catalog.html
> +                      <input class="range-input range-input-till" type="number" value="0">
теперь все сделано, не дергается 👍

2023-03-07 01:15 UTC, kamunicorn commented on styles/styles.css
> +  outline: 3px solid #000000;
я про тень, которая серая
![image](https://user-images.githubusercontent.com/38280676/223288254-9cb9c8c4-a253-4213-853a-c73be7b4e6d0.png)

2023-03-07 01:15 UTC, kamunicorn commented on index.html
> +              <span class="tooltip-text" role="tooltip" id="tooltip-label-date">
У нас есть инпуты и кнопки, которым тоже можно было бы его добавить (атрибут) и связать с информацией об этих инпутах и кнопках. Это не обязательно, на подумать

2023-03-07 01:17 UTC, merged